### ISSUE TITLE
Memory leak related to camera processing

### ISSUE THREAD

**Issue by btelman96** [btelman96/runmyrobot_android#73]
Memory leak crash on Galaxy S4.

This may have been related to a really bad network configuration, but still should not crash like this.

Worth noting that this was about 1 minute into connection.

v0.4 has had about 3 to 4 hours on a Samsung Galaxy S4 and 3 to 4 hours on a Motorola Moto Z, and did not crash then when the network was fast

Solution could either be to fix it, or if the solution cannot be found, auto restart the robot activity and run any time it crashes.

```
11-14 20:01:59.682 6087-14655/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
    Process: com.runmyrobot.android_robot_for_phone, PID: 6087
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 16476 byte allocation with 9316 free bytes and 9KB until OOM
        at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
        at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:146)
        at java.lang.StringBuilder.append(StringBuilder.java:216)
        at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.checkAndUpdateProcess(FFmpegExecuteAsyncTask.java:110)
        at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:46)
        at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by btelman96** [comment]
Starting to investigate

**Comment by btelman96** [comment]
Moto Z Profiling data
![image](https://user-images.githubusercontent.com/4467863/48747937-bdb7d580-ec3a-11e8-9f70-01e60b1a935e.png)

**Comment by btelman96** [comment]
332bcd5 only fixes leaking issues with camera2. The main leak still exists

**Comment by btelman96** [comment]
How this happened:

Frames are sent to an android handler. If the phone cannot process data fast enough or the network is too slow for given bitrate, objects will start to pool up. each time a frame is processed, the pool is eliminated, but if it goes too long without sending a frame, it builds up to the point where the app crashes.

This now will not queue data to the handler unless the handler has no data at all

**Comment by btelman96** [comment]
Moto Z profiling. 1920x1080 at 10Mbps, which was really laggy. Saw no bad memory spikes
![image](https://user-images.githubusercontent.com/4467863/48877098-3ba8e780-edc7-11e8-8c46-28c56bc5fcc1.png)
